name = "Baito"
uuid = "64fab020-fbef-4762-8ecb-2dc867f5f1fd"
repo = "https://github.com/Baffelan/Baito.jl"
description = "Baffelan's shed for Julia's packages"

[packages]
2cbcc540-60d5-4e59-8d77-8826b4db9639 = { name = "Stranbo", path = "S/Stranbo" }
59f707cc-cce7-40fd-9617-9e0c6ce07bf2 = { name = "IOM_WritePostgres", path = "I/IOM_WritePostgres" }
bdf42eb1-85ec-4052-9919-edfefbcacadc = { name = "IOM_Collector", path = "I/IOM_Collector" }
